from typing import Dict, Set, NamedTuple
from enum import IntFlag, auto


class ItemCat(IntFlag):
    ITEM = auto()
    WEAPON = auto()
    ARMOR = auto()
    SKILL = auto()
    RECRUIT = auto()  # also used for roommates like wiggly fred and the masked shadow
    MISC = auto()  # used for switch defined items - crafting kit, crosswords, sams arms, elevator, etc
    RESOURCE_PACK = auto()
    TRAP = auto()


class ItemTag(IntFlag):
    USEFUL = auto()
    INGREDIENT = auto()
    CHECK_GATE = auto()  # all keys or items that can be turned in for a location
    OFFERING = auto()
    BREAKABLE_KEY = auto()
    PROGRESSIVE = auto()
    SPECIAL_CURRENCY = auto()
    UNIQUE = auto()


class ItemData(NamedTuple):
    category: ItemCat
    tags: Set[ItemTag]
    category_id: int


def get_item_id(item_data: ItemData) -> int:
    match item_data.category:
        case ItemCat.ITEM:
            return item_data.category_id
        case ItemCat.WEAPON:
            return item_data.category_id + 1000
        case ItemCat.ARMOR:
            return item_data.category_id + 2000
        case ItemCat.SKILL:
            return item_data.category_id + 3000
        case ItemCat.RECRUIT:
            return item_data.category_id + 4000
        case ItemCat.MISC:
            return item_data.category_id + 5000
        case ItemCat.RESOURCE_PACK:
            return item_data.category_id + 6000
        case ItemCat.TRAP:
            return item_data.category_id + 7000
    return item_data.category_id


main_item_table: dict[str, ItemData] = {
    "Healing Spray": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 2),
    "Suturing Kit": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.UNIQUE}, 3),
    "Medic-in-a-jar": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 4),
    "Rat Baby Thing": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 5),
    "Eye Drops": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 6),
    "Bandage": ItemData(ItemCat.ITEM, set(), 7),
    "Tonic": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 8),
    "First Aid Kit": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 9),
    "Balm": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 10),
    "Antidote": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 11),
    "Smelling Salts": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 12),
    "Disinfectant": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 13),
    "Medication": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 14),
    "Stimulant": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 15),
    "Elixir": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 16),
    "Anxiety Meds": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 17),
    "Bag of Chips": ItemData(ItemCat.ITEM, set(), 18),
    "Spicy Chips": ItemData(ItemCat.ITEM, set(), 19),
    "Onion-Os": ItemData(ItemCat.ITEM, set(), 20),
    "Cheez-Stix": ItemData(ItemCat.ITEM, set(), 21),
    "Chocky Bar": ItemData(ItemCat.ITEM, set(), 22),
    "Granola Bar": ItemData(ItemCat.ITEM, set(), 23),
    "Muffin": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 24),
    "Bocky": ItemData(ItemCat.ITEM, set(), 25),
    "Hard Candy": ItemData(ItemCat.ITEM, set(), 26),
    "Mint Gum": ItemData(ItemCat.ITEM, set(), 27),
    "Gummi Bears": ItemData(ItemCat.ITEM, set(), 28),
    "Worm-Baked Pie": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 29),
    "Succulent Fruit??": ItemData(ItemCat.ITEM, set(), 30),
    "Tonic+??": ItemData(ItemCat.ITEM, set(), 33),
    "Cheese Wedge": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 34),
    "M dic#t10n": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 35),
    "Cola Can": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 36),
    "Lemon Drink Can": ItemData(ItemCat.ITEM, set(), 37),
    "Orange Drink Can": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 38),
    "Juice Box": ItemData(ItemCat.ITEM, set(), 39),
    "Cold Coffee": ItemData(ItemCat.ITEM, set(), 40),
    "Coffee": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 41),
    "Beer": ItemData(ItemCat.ITEM, set(), 42),
    "Whiskey": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.INGREDIENT}, 43),
    "Vodka": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.INGREDIENT}, 44),
    "Energy Drink": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 45),
    "Worm Juice": ItemData(ItemCat.ITEM, set(), 46),
    "Dangerous Brew": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 47),
    "Worm Perfume": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 48),
    "Rotten Leftovers": ItemData(ItemCat.ITEM, set(), 49),
    "Leftovers": ItemData(ItemCat.ITEM, set(), 50),
    "Chicken Sandwich": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 51),
    "Egg Salad Sandwich": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 52),
    "Tomato Sandwich": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 53),
    "Ham Sandwich": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 54),
    "Burrito": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 55),
    "Fred's Hoagie": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 56),
    "Rotten Pizza Slice": ItemData(ItemCat.ITEM, set(), 57),
    "Stale Pizza Slice": ItemData(ItemCat.ITEM, set(), 58),
    "Cheese Pizza Slice": ItemData(ItemCat.ITEM, set(), 59),
    "Italian Pizza Slice": ItemData(ItemCat.ITEM, set(), 60),
    "All-Dressed Pizza Slice": ItemData(ItemCat.ITEM, set(), 61),
    "Pineapple Pizza Slice": ItemData(ItemCat.ITEM, set(), 62),
    "Vegetarian Pizza Slice": ItemData(ItemCat.ITEM, set(), 63),
    "Meat Lover's Pizza Slice": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 64),
    "Chicken Pizza Slice": ItemData(ItemCat.ITEM, set(), 65),
    "Deluxe Pizza Slice": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 66),
    "Screaming Pizza Slice": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 67),
    "Hot Cocoa": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 68),
    "Sewage Cocktail": ItemData(ItemCat.ITEM, set(), 69),
    "Fred's Burrito": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 70),
    "Packed Meal": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 71),
    "Fruit Slice": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 72),
    "Silver Dust": ItemData(ItemCat.ITEM, set(), 73),
    "Combat Surge": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE, ItemTag.USEFUL}, 74),
    "Invulnerable Syringe": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.UNIQUE}, 75),
    "Wrapped Gift": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 76),
    "Ammo Crate": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 77),
    "Super Explosive": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 79),
    "Fire Bomb": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 80),
    "Tumor Lump": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 81),
    "Filth Bomb": ItemData(ItemCat.ITEM, set(), 82),
    "Fingernail Bomb": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 83),
    "Tame Landmine": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.UNIQUE}, 85),
    "Tranquilizer": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 86),
    "Turpentine": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 87),
    "Shadow Bomb": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 88),
    "Acid Flask": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 89),
    "Gas Bomb": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 90),
    "Explosive": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 91),
    "Dinner Plate": ItemData(ItemCat.ITEM, set(), 92),
    "Snowball": ItemData(ItemCat.ITEM, set(), 93),
    "Bottle": ItemData(ItemCat.ITEM, set(), 94),
    "Table Fork": ItemData(ItemCat.ITEM, set(), 95),
    "Table Knife": ItemData(ItemCat.ITEM, set(), 96),
    "Bowling Ball": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 97),
    "Throwing Dart": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 98),
    "Throwing Knife": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 99),
    "Molotov": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 100),
    "Grenade": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 101),
    "Shuriken": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 102),
    "Blood Clot Bomb": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 103),
    "Teddy": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 104),
    "Chew Toy": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 112),
    "Mocha Latte": ItemData(ItemCat.ITEM, set(), 119),
    "Honeycomb": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 120),
    "Hling Spr ay": ItemData(ItemCat.ITEM, set(), 126),
    "Worm Bomb": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 127),
    "Marc-André": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.UNIQUE}, 129),
    "All-Seeing 8-Ball": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.UNIQUE}, 130),
    "Special Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 132),
    "Rare Mint Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 133),
    "Rare Lime Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 134),
    "Rare Banana Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 135),
    "Rare Cherry Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 136),
    "Rare Soda Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 137),
    "Rare Licorice Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 138),
    "Hellfire Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 139),
    "Nectar Candy": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 140),
    "Cheese Man": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 142),
    "Pale Fluid": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 147),
    "Black Ooze": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT, ItemTag.SPECIAL_CURRENCY}, 148),
    "Caustic Brew": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 149),
    "Cloth": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 150),
    "Detonator": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 151),
    "Radio": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 156),
    "Reagent": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 158),
    "Enzyme": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 159),
    "Catalyst": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 160),
    "Vinegar": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 161),
    "Gasoline": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 162),
    "D-Clogger": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 163),
    "Klysox": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 164),
    "Medicell": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 165),
    "Purocare": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 166),
    "Cleanerex": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 167),
    "Herbicide": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 168),
    "Roach": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 170),
    "Mushroom": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 172),
    "Soap": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 173),
    "Toothpaste": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 174),
    "Duct Tape": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 176),
    "Junk": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 177),
    "TV Dinner": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 212),
    "Frozen Pizza": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 213),
    "Pizza Bites": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 214),
    "Frozen Veggies": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 215),
    "Frozen Fish": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 216),
    "Instant Noodles": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 219),
    "Stew Mix Carton": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 220),
    "Can o' Beans": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 221),
    "Rice": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 222),
    "Potatoes": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 223),
    "Tomato Can": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 224),
    "Bread": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 227),
    "Raw Pork": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 228),
    "Raw Chicken": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 229),
    "Raw Beef": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 230),
    "Eggs": ItemData(ItemCat.ITEM, {ItemTag.INGREDIENT}, 231),
    "Baby's Drawings": ItemData(ItemCat.ITEM, set(), 234),
    "Child's Drawings": ItemData(ItemCat.ITEM, set(), 235),
    "Drawings": ItemData(ItemCat.ITEM, set(), 236),
    "Jewelry Box": ItemData(ItemCat.ITEM, set(), 237),
    "Anime Figure": ItemData(ItemCat.ITEM, set(), 238),
    "Spirit Board": ItemData(ItemCat.ITEM, set(), 239),
    "Puzzle Cube": ItemData(ItemCat.ITEM, set(), 240),
    "Comic Books": ItemData(ItemCat.ITEM, set(), 241),
    "Rare Comic Book": ItemData(ItemCat.ITEM, set(), 242),
    "Tarot Deck": ItemData(ItemCat.ITEM, set(), 243),
    "Card Deck": ItemData(ItemCat.ITEM, set(), 244),
    "Backgammon Set": ItemData(ItemCat.ITEM, set(), 245),
    "Old Chessboard": ItemData(ItemCat.ITEM, set(), 246),
    "Mazes & Wizards": ItemData(ItemCat.ITEM, set(), 247),
    "Tea Set": ItemData(ItemCat.ITEM, set(), 248),
    "Hockey Trophy": ItemData(ItemCat.ITEM, set(), 249),
    "Grandma's Urn": ItemData(ItemCat.ITEM, set(), 250),
    "Photo Album": ItemData(ItemCat.ITEM, set(), 251),
    "Old Picture": ItemData(ItemCat.ITEM, set(), 252),
    "Silverware Box": ItemData(ItemCat.ITEM, set(), 253),
    "Stamp Collection": ItemData(ItemCat.ITEM, set(), 254),
    "Box of Seashells": ItemData(ItemCat.ITEM, set(), 255),
    "Musical Box": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 256),
    "Elephant Statuette": ItemData(ItemCat.ITEM, set(), 257),
    "Kitsch Lamp": ItemData(ItemCat.ITEM, set(), 258),
    "Coin Collection": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 259),
    "Carved Beaver": ItemData(ItemCat.ITEM, set(), 260),
    "Taxidermy Dog": ItemData(ItemCat.ITEM, set(), 261),
    "Taxidermy Eagle": ItemData(ItemCat.ITEM, set(), 262),
    "Taxidermy Creature": ItemData(ItemCat.ITEM, set(), 263),
    "Taxidermy Squirrel": ItemData(ItemCat.ITEM, set(), 264),
    "Beer Stein": ItemData(ItemCat.ITEM, set(), 265),
    "Stack of Magazines": ItemData(ItemCat.ITEM, set(), 266),
    "Dirty Magazines": ItemData(ItemCat.ITEM, set(), 267),
    "Handbag": ItemData(ItemCat.ITEM, set(), 268),
    "Old Speakers": ItemData(ItemCat.ITEM, set(), 269),
    "Manga Pile": ItemData(ItemCat.ITEM, set(), 270),
    "Old Game Console": ItemData(ItemCat.ITEM, set(), 271),
    "Vintage Game Console": ItemData(ItemCat.ITEM, set(), 272),
    "Hockey Cards": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 273),
    "Baseball Cards": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 274),
    "Old Records": ItemData(ItemCat.ITEM, set(), 275),
    "Old CDs": ItemData(ItemCat.ITEM, set(), 276),
    "GameKid Color": ItemData(ItemCat.ITEM, set(), 277),
    "Watch": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 280),
    "Fitness Tracker": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 281),
    "Old Mail": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 285),
    "Ice Melt Salt": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.BREAKABLE_KEY}, 286),
    "Length of Rope": ItemData(ItemCat.ITEM, set(), 287),
    "Sapper Charge": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.BREAKABLE_KEY }, 289),
    "Defused Mine": ItemData(ItemCat.ITEM, set(), 290),
    "Dog Tags": ItemData(ItemCat.ITEM, {ItemTag.SPECIAL_CURRENCY}, 291),
    "Supply Crate": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 292),
    "Painter's Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 293),
    "Stained Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 294),
    "Twilight Valve": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 296),
    "Midnight Valve": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 297),
    "Abyssal Valve": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 298),
    "Hadal Valve": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 299),
    "Apt. 33 Key": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 300),
    "Padlock Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 301),
    "Apt. 21 Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 302),
    "Basement Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 303),
    "Store Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 304),
    "Child Barrier Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 305),
    "Janitor Key Ring": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 306),
    "Door Knob": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 310),
    "Army Guy Figure": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 311),
    "Roof Access Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 314),
    "Dark Room Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 315),
    "Love Letter": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 316),
    "Stationery": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 317),
    "Fountain Pen": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 318),
    "Batteries": ItemData(ItemCat.ITEM, set(), 319),
    "Simple Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.BREAKABLE_KEY}, 320),
    "Sun Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 321),
    "Mercury Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 322),
    "Venus Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 323),
    "Earth Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 324),
    "Mars Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 325),
    "Jupiter Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 326),
    "Saturn Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 327),
    "Uranus Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 328),
    "Neptune Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 329),
    "Pluto Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 330),
    "Void Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 331),
    "Negative Disc": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 332),
    "Guinea Pig": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.OFFERING, ItemTag.UNIQUE}, 334),
    "Blank VHS tape": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.OFFERING, ItemTag.UNIQUE}, 335),
    "Incorrect CCTV Recording": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 336),
    "Correct CCTV Recording": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 337),
    "Photo Paper": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 338),
    "Exposed Paper": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 339),
    "Correct Photograph": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 340),
    "Canvas Carry Bag": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 341),
    "Incorrect Painting": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 342),
    "Correct Painting": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 343),
    "Crumpled Manuscript": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 344),
    "Clean Manuscript": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.UNIQUE}, 345),
    "Progressive Loose Manuscript": ItemData(ItemCat.ITEM, {ItemTag.OFFERING, ItemTag.PROGRESSIVE}, 346),
    "Clown Drawing": ItemData(ItemCat.ITEM, set(), 347),
    "Metro Ticket": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 349),
    "Tongue": ItemData(ItemCat.ITEM, set(), 350),
    "Foot": ItemData(ItemCat.ITEM, set(), 351),
    "Ear": ItemData(ItemCat.ITEM, set(), 352),
    "Tooth": ItemData(ItemCat.ITEM, set(), 353),
    "Eye": ItemData(ItemCat.ITEM, set(), 354),
    "Hand": ItemData(ItemCat.ITEM, set(), 355),
    "Heart": ItemData(ItemCat.ITEM, set(), 356),
    "Intestines": ItemData(ItemCat.ITEM, set(), 357),
    "Brain": ItemData(ItemCat.ITEM, set(), 358),
    "Cassette Tape": ItemData(ItemCat.ITEM, {ItemTag.SPECIAL_CURRENCY}, 359),
    "Rose": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 360),
    "Four-Leaf Clover": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 361),
    "Torn-Off Face": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 362),
    "Lockpicks": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 363),
    "Electronic Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 364),
    "Empty Photograph": ItemData(ItemCat.ITEM, {ItemTag.OFFERING}, 365),
    "Tickle's Gift": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 367),
    "Phillippe's Remains": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 368),
    "Trophy": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 369),
    "Coffee Machine": ItemData(ItemCat.ITEM, {ItemTag.USEFUL, ItemTag.UNIQUE}, 370),
    "Vending Machine Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 371),
    "Laundry": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 373),
    "Rat Tail": ItemData(ItemCat.ITEM, {ItemTag.SPECIAL_CURRENCY}, 375),
    "NeoDuo": ItemData(ItemCat.ITEM, set(), 376),
    "Eugene's Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 377),
    "Shrunken Head": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 378),
    "Plumbing Tools": ItemData(ItemCat.ITEM, set(), 379),
    "Potting Soil": ItemData(ItemCat.ITEM, set(), 381),
    "Worm Egg": ItemData(ItemCat.ITEM, {ItemTag.SPECIAL_CURRENCY}, 382),
    "Antoine's Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 383),
    "Jasper's Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 384),
    "Apt. 35 Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 385),
    "Telescope Pieces": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 386),
    "Telescope": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 387),
    "Small Red Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 388),
    "Phone": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE}, 389),
    "Last Will": ItemData(ItemCat.ITEM, {ItemTag.OFFERING}, 390),
    "Old Tape": ItemData(ItemCat.ITEM, {ItemTag.OFFERING}, 391),
    "Old Photograph": ItemData(ItemCat.ITEM, {ItemTag.OFFERING}, 392),
    "Wrapped Painting": ItemData(ItemCat.ITEM, {ItemTag.OFFERING}, 393),
    "Iris Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.BREAKABLE_KEY}, 395),
    "Rebreather": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 396),
    "Cooking Book": ItemData(ItemCat.ITEM, set(), 397),
    "Strange Key": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE, ItemTag.CHECK_GATE}, 398),
    "Old Key": ItemData(ItemCat.ITEM, set(), 399),
    "Clyde's Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 403),
    "Jennifer's Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 404),
    "Auguste's Key": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 405),
    "Wake the Blood Knight": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 411),
    "Wizards Hell: Arcane Tears": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 412),
    "Super Jumplad": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 413),
    "Super Jumplad 3": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 414),
    "Catafalque": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 415),
    "Honko's Grand Journey": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 416),
    "Madwheels 97": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 417),
    "Wraithscourge": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 418),
    "Massacre Princess": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 419),
    "Kill to Shoot": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 420),
    "Myrmidon": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 421),
    "Myrmidon XII": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 422),
    "Screamatorium": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 423),
    "Frogit About It": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 424),
    "Blood Ghoul Orgy 3": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 425),
    "Octocook": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 426),
    "Space Truckerz": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 427),
    "Reptile Football": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 428),
    "Auntie Wilma's Crossword Challenge": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 429),
    "Unlabeled Cartridge": ItemData(ItemCat.ITEM, {ItemTag.CHECK_GATE, ItemTag.UNIQUE}, 430),
    "Dustin Figure": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 433),
    "Ratavia Figure": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 434),
    "Musk Figure": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 435),
    "Jacket Figure": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 436),
    "Lute Figure": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 437),
    "Cerulean Figure": ItemData(ItemCat.ITEM, {ItemTag.UNIQUE}, 438),
    "green key": ItemData(ItemCat.ITEM, {ItemTag.BREAKABLE_KEY}, 651),
    "red key": ItemData(ItemCat.ITEM, {ItemTag.BREAKABLE_KEY}, 652),
    "yellow key": ItemData(ItemCat.ITEM, {ItemTag.BREAKABLE_KEY}, 653),
    "blue key": ItemData(ItemCat.ITEM, {ItemTag.BREAKABLE_KEY}, 654),
    "white key": ItemData(ItemCat.ITEM, {ItemTag.BREAKABLE_KEY}, 655),
    "black key": ItemData(ItemCat.ITEM, {ItemTag.BREAKABLE_KEY}, 656),
    "Scroll of Shatter": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 470),
    "Scroll of Incision": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 471),
    "Scroll of Impale": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 472),
    "Scroll of Burn": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 473),
    "Scroll of Blind": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 474),
    "Scroll of Decay": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 475),
    "Scroll of Heal": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 476),
    "Curse of Frogs": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 477),
    "Curse of Brittle Bones": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 478),
    "Curse of Seizures": ItemData(ItemCat.ITEM, {ItemTag.USEFUL}, 479)
}

skill_table: dict[str, ItemData] = {
    "Jump Attack": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 401),
    "Nitro Boost": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 402),
    "Combat Medic": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 403),
    "Screamer": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 404),
    "Numbness": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 405),
    "Croak Orders": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 406),
    "Hurt Me Plenty": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 407),
    "Octostrike": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 408),
    "Meteor Strike": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE, ItemTag.CHECK_GATE}, 409),
    "Painful Stab": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 410),
    "Aim The Killshot": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 411),
    "Cash Sock": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 412),
    "Blood Madness": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 413),
    "Long Haul Flow": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 414),
    "Running Tackle": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 415),
    "Dungeon Dance": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 416),
    "Garrison": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 417),
    "Risk Taker": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 418),
    "Confusing Word": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 419),
    "Tadasana": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 920),
    "Unleashed Beast": ItemData(ItemCat.SKILL, {ItemTag.UNIQUE}, 103),
}

weapon_table: dict[str, ItemData] = {
    "Broken Handle": ItemData(ItemCat.WEAPON, set(), 7),
    "Broom": ItemData(ItemCat.WEAPON, set(), 8),
    "Nightstick": ItemData(ItemCat.WEAPON, set(), 10),
    "Bottle": ItemData(ItemCat.WEAPON, set(), 12),
    "Baseball Bat": ItemData(ItemCat.WEAPON, set(), 15),
    "Frying Pan": ItemData(ItemCat.WEAPON, set(), 17),
    "Golf Club": ItemData(ItemCat.WEAPON, set(), 19),
    "Folding Chair": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 21),
    "Candlestick": ItemData(ItemCat.WEAPON, set(), 23),
    "Mop": ItemData(ItemCat.WEAPON, set(), 25),
    "Hammer": ItemData(ItemCat.WEAPON, set(), 27),
    "Sledgehammer": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 29),
    "Metal Bat": ItemData(ItemCat.WEAPON, set(), 31),
    "Mace": ItemData(ItemCat.WEAPON, set(), 33),
    "Rolling Pin": ItemData(ItemCat.WEAPON, set(), 36),
    "Ernest's Metal Bat": ItemData(ItemCat.WEAPON, set(), 38),
    "Carving Fork": ItemData(ItemCat.WEAPON, set(), 42),
    "Pool Cue": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 44),
    "Rake": ItemData(ItemCat.WEAPON, set(), 46),
    "Dagger": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 48),
    "Spade": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 50),
    "Pitchfork": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 52),
    "Rapier": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 54),
    "Spear": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 56),
    "Venom Dagger": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 58),
    "Steak Knife": ItemData(ItemCat.WEAPON, set(), 62),
    "Bread Knife": ItemData(ItemCat.WEAPON, set(), 64),
    "Old Axe": ItemData(ItemCat.WEAPON, set(), 66),
    "Chef's Knife": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 68),
    "Cleaver": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 70),
    "Fireman's Axe": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 72),
    "Claymore": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 74),
    "Machete": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 77),
    "Katana": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 79),
    "Combat Knife": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 81),
    "Scalpel": ItemData(ItemCat.WEAPON, set(), 83),
    "Kitchen Knife": ItemData(ItemCat.WEAPON, set(), 85),
    "Hellen's Cleaver": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 87),
    "Fuzzy": ItemData(ItemCat.WEAPON, set(), 91),
    "Sheathed Katana": ItemData(ItemCat.WEAPON, set(), 94),
    "Greatsword?": ItemData(ItemCat.WEAPON, set(), 97),
    "Mosquito Knife": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 98),
    "Stun Baton": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 100),
    "Chainsaw": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 103),
    "Cattle Prod Spear": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 106),
    "Rat Tail Whip": ItemData(ItemCat.WEAPON, set(), 110),
    "Rat Claws": ItemData(ItemCat.WEAPON, set(), 112),
    "Sewage Blade": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 114),
    "Hockey Stick": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 116),
    "Joyeuse": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 118),
    "Bone Saw": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 120),
    "Metal Detector": ItemData(ItemCat.WEAPON, set(), 122),
    "Shadow Blade": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 125),
    "Shadow Knife": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 127),
    "Misshapen Limb": ItemData(ItemCat.WEAPON, set(), 130),
    "Patchwork Club": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 133),
    "Great Needle": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 135),
    "Testsword": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 138),
    "Testsword mk2": ItemData(ItemCat.WEAPON, set(), 139),
    "Hellsword": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 141),
    "Jawbone Club": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 143),
    "Furnace Edge": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 145),
    "Pizza Cutter": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 151),
    "Wordsmith's Hammer": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 154),
    "Spear of the Word": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 156),
    "Spellsword": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 158),
    "Worm O' Nine Tails": ItemData(ItemCat.WEAPON, set(), 162),
    "Stained Shears": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 165),
    "Angel's Bat": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 167),
    "Fluff Ball": ItemData(ItemCat.WEAPON, set(), 170),
    "Fuzzy's Remains": ItemData(ItemCat.WEAPON, set(), 171),
    "Repaired Fuzzy": ItemData(ItemCat.WEAPON, set(), 172),
    "Mangled Fuzzy": ItemData(ItemCat.WEAPON, set(), 173),
    "Renegade Fuzzy": ItemData(ItemCat.WEAPON, set(), 174),
    "Worm Fuzzy": ItemData(ItemCat.WEAPON, set(), 175),
    "Gardening Shears": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 178),
    "Heirloom Greatsword": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 180),
    "Demon Knuckles": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 182),
    "World Tree's Bane": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 184),
    "Sky Piercer": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 186),
    "Wizards' Staff": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 188),
    "Rabu Hammer": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 190),
    "Rotten Fang": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 194),
    "Voidblade": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 196),
    "Whisperblade": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 201),
    "Snake Whip": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 206),
    "Antenniform Legs": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 209),
    "Azure Greatsword": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 211),
    "Right Claw": ItemData(ItemCat.WEAPON, set(), 213),
    "Toothy Whip": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 215),
    "Tooth Knife": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 217),
    "Tooth Scimitar": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 219),
    "Tooth Hammer": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 221),
    "Junk Sword": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 225),
    "Me[ttal Ba2t": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 230),
    "Ocular Tetherblade": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 241),
    "Mossy Hammer": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 243),
    "Goblin's Claws": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 246),
    "Spine Dagger": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 251),
    "Icicle Spike": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 255),
    "Electroclaw": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 260),
    "Hadal Trident": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 263),
    "Dual Metal Bat": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 266),
    "Dual Rapier": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 269),
    "Dual Machete": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 272),
    "Slime Spear": ItemData(ItemCat.WEAPON, {ItemTag.USEFUL}, 275)
}

armor_table: dict[str, ItemData] = {
    "Rags": ItemData(ItemCat.ARMOR, set(), 2),
    "Polo Shirt": ItemData(ItemCat.ARMOR, set(), 3),
    "Button-Up Shirt": ItemData(ItemCat.ARMOR, set(), 4),
    "T-Shirt": ItemData(ItemCat.ARMOR, set(), 5),
    "Tank Top": ItemData(ItemCat.ARMOR, set(), 6),
    "Hoodie": ItemData(ItemCat.ARMOR, set(), 7),
    "Christmas Sweater": ItemData(ItemCat.ARMOR, set(), 8),
    "Denim Vest": ItemData(ItemCat.ARMOR, set(), 9),
    "Windbreaker Jacket": ItemData(ItemCat.ARMOR, set(), 10),
    "Leather Vest": ItemData(ItemCat.ARMOR, set(), 11),
    "Winter Coat": ItemData(ItemCat.ARMOR, set(), 12),
    "Trench Coat": ItemData(ItemCat.ARMOR, set(), 13),
    "Padded Jacket": ItemData(ItemCat.ARMOR, set(), 14),
    "Army Jacket": ItemData(ItemCat.ARMOR, set(), 15),
    "Chest Guard": ItemData(ItemCat.ARMOR, set(), 16),
    "Hauberk": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 17),
    "Breastplate": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 18),
    "Flak Jacket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 19),
    "Kevlar Suit": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 20),
    "Studded Jacket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 21),
    "Strange Robe": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 22),
    "Dark Robes": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 23),
    "Mackinaw Jacket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 24),
    "Old Uniform": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 25),
    "Elegant Suit": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 26),
    "Monty's Jacket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 28),
    "Floral Shirt": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 29),
    "Painter's Beret": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 40),
    "Giant Rat Skull": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 41),
    "Rusty Crown": ItemData(ItemCat.ARMOR, {ItemTag.CHECK_GATE, ItemTag.USEFUL}, 42),
    "Gas Mask": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 43),
    "Shockskull": ItemData(ItemCat.ARMOR, set(), 44),
    "Headband": ItemData(ItemCat.ARMOR, set(), 46),
    "Wool Cap": ItemData(ItemCat.ARMOR, set(), 47),
    "Baseball Cap": ItemData(ItemCat.ARMOR, set(), 48),
    "Cowboy Hat": ItemData(ItemCat.ARMOR, set(), 49),
    "Colander": ItemData(ItemCat.ARMOR, set(), 50),
    "Saucepan": ItemData(ItemCat.ARMOR, set(), 51),
    "Clown Wig and Nose": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 52),
    "Trilby": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 53),
    "Top Hat": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 54),
    "Bowler Hat": ItemData(ItemCat.ARMOR, set(), 55),
    "Bicycle Helmet": ItemData(ItemCat.ARMOR, set(), 56),
    "Hard Hat": ItemData(ItemCat.ARMOR, set(), 57),
    "Football Helmet": ItemData(ItemCat.ARMOR, set(), 58),
    "Hockey Helmet": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 59),
    "Army Helmet": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 60),
    "Pickelhaube": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 61),
    "Motorcycle Helmet": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 62),
    "Welding Helmet": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 63),
    "Dinosaur Helmet": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 65),
    "Circlet of Reason": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 66),
    "Indigo Hockey Mask": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 67),
    "Arrowed Sash": ItemData(ItemCat.ARMOR, set(), 69),
    "Scarf": ItemData(ItemCat.ARMOR, set(), 70),
    "Four of Spades": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 71),
    "Rat Tail Belt": ItemData(ItemCat.ARMOR, set(), 72),
    "Glasses": ItemData(ItemCat.ARMOR, set(), 73),
    "Shades": ItemData(ItemCat.ARMOR, set(), 74),
    "Tie": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 75),
    "Training Belt": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 76),
    "Comfort Belt": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 77),
    "Champion's Belt": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 78),
    "Gloves": ItemData(ItemCat.ARMOR, set(), 79),
    "Plastic Gloves": ItemData(ItemCat.ARMOR, set(), 80),
    "Trauma Kit": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 81),
    "Dress Shoes": ItemData(ItemCat.ARMOR, set(), 83),
    "Running Shoes": ItemData(ItemCat.ARMOR, set(), 84),
    "Rubber Boots": ItemData(ItemCat.ARMOR, set(), 85),
    "Clogs": ItemData(ItemCat.ARMOR, set(), 86),
    "Winter Boots": ItemData(ItemCat.ARMOR, set(), 87),
    "Army Boots": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 88),
    "Work Boots": ItemData(ItemCat.ARMOR, set(), 89),
    "Cowboy Boots": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 90),
    "Vintage Sneakers": ItemData(ItemCat.ARMOR, set(), 91),
    "High Heels": ItemData(ItemCat.ARMOR, set(), 92),
    "Jade Earrings": ItemData(ItemCat.ARMOR, set(), 94),
    "Golden Locket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 95),
    "Gold Ring": ItemData(ItemCat.ARMOR, set(), 96),
    "Ruby Ring": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 97),
    "Emerald Ring": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 98),
    "Sapphire Ring": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 99),
    "Odd Necklace": ItemData(ItemCat.ARMOR, set(), 100),
    "Copper Bangle": ItemData(ItemCat.ARMOR, set(), 101),
    "Silver Bracelet": ItemData(ItemCat.ARMOR, set(), 102),
    "Teeth Pendant": ItemData(ItemCat.ARMOR, set(), 103),
    "Gold Bracelet": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 104),
    "Lapis Band": ItemData(ItemCat.ARMOR, set(), 105),
    "Eye Amulet": ItemData(ItemCat.ARMOR, set(), 106),
    "Ring of Alertness": ItemData(ItemCat.ARMOR, set(), 107),
    "Carnelian Ring": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 108),
    "Ring of Purity": ItemData(ItemCat.ARMOR, set(), 109),
    "Asbestos Amulet": ItemData(ItemCat.ARMOR, set(), 110),
    "Pistol": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 115),
    "Custom Handgun": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 119),
    "Magnum": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 123),
    "SMG": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 128),
    "Old Rifle": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 132),
    "Hunting Shotgun": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 136),
    "Shotgun": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 140),
    "High-Caliber Rifle": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 145),
    "Gatling Gun": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 149),
    "Flamethrower": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 153),
    "Acid Sprayer": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 157),
    "Crossbow": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 160),
    "Dart Gun": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 168),
    "Grenade Launcher": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 173),
    "Slingshot": ItemData(ItemCat.ARMOR, set(), 178),
    "Super Slingshot": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 179),
    "Shadow Gun": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 184),
    "Eyeball Hat": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 189),
    "Chill Touch": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 194),
    "Silver Magnum": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 199),
    "SMG Special": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 204),
    "War Rifle": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 208),
    "Babylon Typewriter": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 212),
    "X-X9 Particle Gun": ItemData(ItemCat.ARMOR, set(), 216),
    "Tooth Rifle": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 224),
    "gun": ItemData(ItemCat.ARMOR, set(), 228),
    "Riot Shield": ItemData(ItemCat.ARMOR, set(), 231),
    "Shroom Cap Shield": ItemData(ItemCat.ARMOR, set(), 232),
    "Heater Shield": ItemData(ItemCat.ARMOR, set(), 233),
    "Fungus Breastplate": ItemData(ItemCat.ARMOR, set(), 244),
    "Fungus Cap?": ItemData(ItemCat.ARMOR, set(), 246),
    "Sabatons": ItemData(ItemCat.ARMOR, set(), 248),
    "Gauntlets": ItemData(ItemCat.ARMOR, set(), 249),
    "Broken Wing": ItemData(ItemCat.ARMOR, set(), 258),
    "Mask of Shadows": ItemData(ItemCat.ARMOR, set(), 259),
    "Midnight Suit": ItemData(ItemCat.ARMOR, set(), 260),
    "Dark Boots": ItemData(ItemCat.ARMOR, set(), 261),
    "Shadow Cloak": ItemData(ItemCat.ARMOR, set(), 262),
    "Shadow Ring": ItemData(ItemCat.ARMOR, set(), 263),
    "Mittens": ItemData(ItemCat.ARMOR, set(), 265),
    "Paint-Stained Apron": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 268),
    "Beret": ItemData(ItemCat.ARMOR, set(), 269),
    "Strange Feather": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 270),
    "Paint Palette": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 271),
    "Cowardly Boots": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 272),
    "War Medal": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 273),
    "Rage Armor": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 274),
    "Headphones": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 276),
    "Biting Boots": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 277),
    "Elbow Pads": ItemData(ItemCat.ARMOR, set(), 278),
    "Crown of Fingers": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 279),
    "Coat of Arms": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 280),
    "Filthy Ring": ItemData(ItemCat.ARMOR, set(), 282),
    "Martin's Ring": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 283),
    "Vampiric Jacket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 285),
    "Blood Cap": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 286),
    "Crimson Ring": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 287),
    "Mycelium Cloak": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 288),
    "Beating Heart": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 289),
    "Tome of Words": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 290),
    "Patchwork Hat": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 291),
    "Patchwork Jacket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 292),
    "Patchwork Boots": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 293),
    "Needle Gloves": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 294),
    "Laser Sight Mount": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 296),
    "Testarmor": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 299),
    "Testarmor mk2": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 300),
    "Papier-Maché Crown": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 330),
    "Official Sash": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 331),
    "Fred Ring": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 334),
    "Straitjacket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 337),
    "Ring of Torment": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 338),
    "Scarlet Scarf": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 340),
    "Yanma Belt": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 341),
    "Wormskin Robe": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 343),
    "Worm Crown": ItemData(ItemCat.ARMOR, set(), 344),
    "Shark Tooth Amulet": ItemData(ItemCat.ARMOR, set(), 346),
    "Sea Cucumber Loafers": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 347),
    "Chrome Finish": ItemData(ItemCat.ARMOR, set(), 351),
    "Chobham Armor": ItemData(ItemCat.ARMOR, set(), 352),
    "Demon Plating": ItemData(ItemCat.ARMOR, set(), 353),
    "Fungus Fibers": ItemData(ItemCat.ARMOR, set(), 354),
    "Rhinoceros Hide": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 355),
    "Tank Tracks": ItemData(ItemCat.ARMOR, set(), 356),
    "Tank Gun": ItemData(ItemCat.ARMOR, set(), 357),
    "Quad Wheels": ItemData(ItemCat.ARMOR, set(), 358),
    "Spiked Bumper": ItemData(ItemCat.ARMOR, set(), 359),
    "Cooler Unit": ItemData(ItemCat.ARMOR, set(), 360),
    "Coffee Unit": ItemData(ItemCat.ARMOR, set(), 361),
    "Carbonator": ItemData(ItemCat.ARMOR, set(), 362),
    "Overdrive Chip": ItemData(ItemCat.ARMOR, set(), 363),
    "Jousting Lance": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 364),
    "Cope Cage": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 365),
    "Dragon Head": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 366),
    "Dragon Body": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 367),
    "Dragon Feet": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 368),
    "Dragon Tail": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 369),
    "Dragon Claw": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 370),
    "Vnage ucky tieakeRs": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 374),
    "RmyJcket": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 375),
    "Ftblhelmt": ItemData(ItemCat.ARMOR, set(), 376),
    "Slime Boots": ItemData(ItemCat.ARMOR, {ItemTag.USEFUL}, 377)
}

misc_table: dict[str, ItemData] = {
    "Aster": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 1),
    "Audrey": ItemData(ItemCat.RECRUIT, {ItemTag.CHECK_GATE}, 2),
    "Joel": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 3),
    "Leigh": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 4),
    "Lyle": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 5),
    "Xaria and Montgomery": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 6),
    "Morton": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 7),
    "Progressive Rat Child": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL, ItemTag.PROGRESSIVE}, 8),
    "Spider": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 9),
    "Hellen": ItemData(ItemCat.RECRUIT, {ItemTag.CHECK_GATE}, 10),
    "Dan": ItemData(ItemCat.RECRUIT, {ItemTag.CHECK_GATE}, 11),
    "Ernest": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 12),
    "Roaches": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 13),
    "Sophie": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 14),
    "Phillippe": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 15),
    "Papineau": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 16),
    "Masked Shadow Roommate": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 17),
    "Wiggly Fred Roommate": ItemData(ItemCat.RECRUIT, {ItemTag.USEFUL}, 18),
    "Player's Left Arm": ItemData(ItemCat.MISC, {ItemTag.USEFUL}, 19),
    "Player's Right Arm": ItemData(ItemCat.MISC, {ItemTag.USEFUL}, 20),
    "Crafting Kit": ItemData(ItemCat.MISC, {ItemTag.USEFUL}, 21),
    "Book of Crossword Puzzles": ItemData(ItemCat.MISC, {ItemTag.CHECK_GATE}, 22),
    "Elevator Activation": ItemData(ItemCat.MISC, {ItemTag.CHECK_GATE}, 23)
}

resource_pack_table: dict[str, ItemData] = {}

item_table: dict[str, ItemData] = {
    **main_item_table,
    **skill_table,
    **weapon_table,
    **armor_table,
    **resource_pack_table,
    **misc_table
}

item_name_groups: dict[str, set[str]] = {
    "OFFERING": {k for k, v in item_table.items() if ItemTag.OFFERING in v.tags},
    "PERFECT_OFFERING": {"Progressive Loose Manuscript",
                         "Correct Painting",
                         "Correct Photograph",
                         "Correct CCTV Recording"},
    "MASK_OFFERING": {"Last Will",
                      "Old Tape",
                      "Old Photograph",
                      "Wrapped Painting"},
    "XIN_AMON_OFFERING": {"Guinea Pig"},
    "BROKEN_TEST_ITEM": {"Testarmor",
                         "Testarmor mk2",
                         "Testsword",
                         "Testsword mk2"},
     "ARM": {"Player's Left Arm", "Player's Right Arm"},
    "NESTOR_QUEST_INTRO": {"Fountain Pen",
                           "Stationery",
                           "Love Letter"},  # should raftas part have to be done before nestors can?
    "CHARACTER_LOCKED_EQUIPMENT": {"Fuzzy"},
    "VIDEO_GAME": {"Wake the Blood Knight",
                  "Wizards Hell: Arcane Tears",
                  "Super Jumplad",
                  "Super Jumplad 3",
                  "Catafalque",
                  "Honko's Grand Journey",
                  "Madwheels 97",
                  "Wraithscourge",
                  "Massacre Princess",
                  "Kill to Shoot",
                  "Myrmidon",
                  "Myrmidon XII",
                  "Screamatorium",
                  "Frogit About It",
                  "Blood Ghoul Orgy 3",
                  "Octocook",
                  "Space Truckerz",
                  "Reptile Football",
                  "Auntie Wilma's Crossword Challenge",
                  "Unlabeled Cartridge"
                  },
}

# map crafting recipe
crafting_recipes: dict[str, set[tuple[str, str]]] = {
    "Molotov": {("Whiskey", "Cloth"), ("Vodka", "Cloth")},
    "Fire Bomb": {("Gasoline", "Cloth")},
    # "Herbicide": set(),
    # todo: fill out
    }


# map each progressive item to the number of upgrades it has
# map each key type to the number of corresponding locks
# todo need to find all numbers
num_multiple_items: Dict[str, int] = {
    "Progressive Loose Manuscript": 2,
    "Progressive Rat Child": 2,
    "Simple Key": 0, # todo: REAL NUMBER
    "green key": 1,
    "red key": 1,
    "yellow key": 2,
    "blue key": 3,
    "white key": 4,
    "black key": 5,
    "Sapper Charge": 0, # todo: REAL NUMBER
    "Iris Key": 0, # todo: REAL NUMBER
    "Ice Melt Salt": 19
}

currency_counts: Dict[str, int] = {
    "Junk": 1,
    "Worm Egg": 1,
    "Casette Tape": 1,

}
